plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = "${project.minecraft_version}-${project.mod_version}-neoforge"
group = mod_group_id

repositories {
    maven { url 'https://jitpack.io' }
    maven {
        url "https://cursemaven.com"
    }
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }


dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.6'

    additionalRuntimeClasspath('io.github.archipelagomw:Java-Client:0.2.1')

    jarJar(implementation ('io.github.archipelagomw:Java-Client:0.2.1'))
    jarJar(implementation ('org.java-websocket:Java-WebSocket:1.5.6'))
    jarJar(implementation ('org.apache.httpcomponents.core5:httpcore5:5.4'))

    compileOnly("curse.maven:ftb-quests-forge-289412:${ftb_quests_version}")
    compileOnly("curse.maven:ftb-library-forge-404465:7746959")

    implementation "curse.maven:ftb-quests-forge-289412:${ftb_quests_version}"
    implementation "curse.maven:ftb-library-forge-404465:8519365"
    implementation "curse.maven:ftb-teams-forge-404468:7369021"
    implementation "curse.maven:architectury-api-419699:5786327"

    implementation "com.github.Stuff691734:archipelago-lib:${archipelago_lib_version}"
    additionalRuntimeClasspath "com.github.Stuff691734:archipelago-lib:${archipelago_lib_version}"
    jarJar (implementation "com.github.Stuff691734:archipelago-lib:${archipelago_lib_version}")
}

configurations.configureEach {
    resolutionStrategy {
        force "com.google.code.gson:gson:2.10.1"
        force "org.slf4j:slf4j-api:2.0.9"
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description,
                            ftb_quests_version      : ftb_quests_version]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
