plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.1.20'
}

version = "${project.minecraft_version}-${project.mod_version}-neoforge"
group = mod_group_id

repositories {
    maven {
        url "https://cursemaven.com"
    }
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)


runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'

        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
        dependencies {
            runtime 'io.github.archipelagomw:Java-Client:0.2.1'
        }
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        arguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }


dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.6'

    implementation('io.github.archipelagomw:Java-Client:0.2.1')
    implementation "net.neoforged:neoforge:${project.neo_version}"

    jarJar(implementation ('io.github.archipelagomw:Java-Client:0.2.1'))
    jarJar(implementation ('org.java-websocket:Java-WebSocket:1.5.6'))
    jarJar(implementation ('org.apache.httpcomponents.core5:httpcore5:5.4'))
}

configurations.configureEach {
    resolutionStrategy {
        force "com.google.code.gson:gson:2.10.1"
        force "org.slf4j:slf4j-api:2.0.9"
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
