org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=archipelago
mod_name=Archipelago
mod_license=Unlicense
mod_version=2.2.8
mod_group_id=net.stuff691734
mod_authors=Stuff691734
mod_description=Adds support for archipelago multiworld randomizer to modded minecraft.

minecraft_version=1.13.2
minecraft_version_range=[1.13.2]
forge_version=25.0.223
forge_version_range=[25,)
loader_version_range=[25,)
mapping_channel=snapshot
mapping_version=20190530-1.13.2