org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=archipelago
mod_name=Archipelago
mod_license=Unlicense
mod_version=3.1.0
mod_group_id=net.stuff691734
mod_authors=Stuff691734
mod_description=Adds support for archipelago multiworld randomizer to modded minecraft.

minecraft_version=1.16.4
minecraft_version_range=[1.16.4]
forge_version=35.1.37
forge_version_range=[35,)
loader_version_range=[35,)
ftb_quests_version=3249257
mapping_channel=official
mapping_version=1.16.4
archipelago_lib_version=0.11.4