org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=archipelago
mod_name=Archipelago
mod_license=Unlicense
mod_version=2.2.7
mod_group_id=net.stuff691734
mod_authors=Stuff691734
mod_description=Adds support for archipelago multiworld randomizer to modded minecraft.

minecraft_version=1.19.1
minecraft_version_range=[1.19.1]
forge_version=42.0.9
forge_version_range=[42,)
loader_version_range=[42,)
mapping_channel=official
mapping_version=1.19.1